title: Open Mainframe Project Artwork
description: >-
  Logos and artwork for the Open Mainframe Project (OMP) and it's hosted projects

# Settings
favicon: other/open-mainframe-project/icon/color/open-mainframe-project-icon-color.svg 
primary_logo: other/open-mainframe-project/horizontal/color/open-mainframe-project-horizontal-color.svg
header_logo: other/open-mainframe-project/horizontal/white/open-mainframe-project-horizontal-white.svg  
github_repo: https://github.com/openmainframeproject/artwork
theme_color_1: 2b7de1 
theme_color_2: 133e76
logo_categories:
  - Active Projects
  - Incubating Projects
  - Working Groups
  - Emeritus Projects
  - Badges
  - Other Logos

readme_index:
  with_frontmatter: true
plugins:
  - jekyll-remote-theme
remote_theme: jmertic/artwork-template
