title: Open Mainframe Project Artwork
description: >-
  Logos and artwork for the Open Mainframe Project (OMP) and it's hosted projects

# Settings
favicon: other/open-mainframe-project/icon/color/open-mainframe-project-icon-color.svg 
primary_logo: other/open-mainframe-project/horizontal/color/open-mainframe-project-horizontal-color.svg
header_logo: other/open-mainframe-project/horizontal/white/open-mainframe-project-horizontal-white.svg  
github_repo: https://github.com/openmainframeproject/artwork
theme_color_1: 2b7de1 
theme_color_2: 133e76
# categories of logos, for grouping on main logo page. Must match level: in front matter of each logoset README.md file
logo_categories:
  - Projects
  - Working Groups
  - Badges
  - Other Logos
ga_tracking_id: 359859504

defaults:
  - scope:
      path: "other"     # directory (relative to site root)
      type: "pages"    # usually "pages"
    values:
      layout: "logos"
      level: "Other Logos"
  - scope:
      path: "badges"     # directory (relative to site root)
      type: "pages"    # usually "pages"
    values:
      layout: "logos"
      level: "Badges"
  - scope:
      path: "projects"     # directory (relative to site root)
      type: "pages"    # usually "pages"
    values:
      layout: "logos"
      level: "Projects"
  - scope:
      path: "working-groups"     # directory (relative to site root)
      type: "pages"    # usually "pages"
    values:
      layout: "logos"
      level: "Working Groups"

# don't touch ;-)
readme_index:
  with_frontmatter: true
plugins:
  - jekyll-remote-theme
remote_theme: jmertic/artwork-template
